version: 2.1

jobs:
  job:
    docker:
      - image: debian:latest
    resource_class: arm.medium

    steps:
      - checkout
      - run:
          name: "Install packages"
          command: "./install.sh"
      - run:
          name: "Fetch source code"
          command: "./fetch.sh"
      - run:
          name: "Build source code"
          command: "./build.sh"
      - run:
          name: "Package binaries"
          command: "./package.sh"

workflows:
  workflow:
    jobs:
      - job
